# Generated by Django 4.1 on 2022-09-22 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payout',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
