# Generated by Django 4.1 on 2022-10-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_traffic_remove_payout_user_delete_deposit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traffic',
            old_name='types',
            new_name='type',
        ),
    ]
