# Generated by Django 4.1 on 2022-10-01 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_rename_types_traffic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
