# Generated by Django 4.1 on 2022-10-01 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_alter_traffic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
